# -*- coding: utf-8 -*-
"""MACHINE LEARNING FROM DISASTER TITANIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMDkMIuzUfyplNs-9NwNaKFz630eIFRG
"""

# 6th dec
# Exploratory Data Analysis - Machine Learning in Titanic disaster

# 1. Take the data and create dataframes

import pandas as pd 
df = pd.read_csv('/content/train.csv')
df

df.shape # provides the number of rows and columns

df.size # provides the total element present in the dataset

df.info() # provides the complete information about the dataset

# to check the null values
df.isnull().sum()

df.nunique()

# VISUALTISATION - SEABORN (ADVANCED THEN MATPLOTLIB)
# This visualisation tells us about the no.of.people survived and not survived
import seaborn as sns
sns.countplot(x='Survived', data=df)

# We want the exact count of survived people
df['Survived'].value_counts()

df.Survived.value_counts()

df.groupby('Survived').size()

# We want to know how many males and how many females were aboard the titanic
df.Sex.value_counts()

# I want the no.of.males survived 
import numpy as np
survived_m = np.sum((df['Sex']=='male')&(df['Survived']==1))
survived_f = np.sum((df['Sex']=='female')&(df['Survived']==1))
nsurvived_m = np.sum((df['Sex']=='male')&(df['Survived']==0))
nsurvived_f = np.sum((df['Sex']=='female')&(df['Survived']==0))
print(nsurvived_f, nsurvived_m, survived_f, survived_m)

# Another method
df.groupby(['Sex', 'Survived']).size()

df[['Sex', 'Survived']].value_counts()

# Now let us divide the Age column's data into 4 different categories

young = np.sum((df['Age']>=0)&(df['Age']<20))
adult = np.sum((df['Age']>=20)&(df['Age']<40))
midage = np.sum((df['Age']>=40)&(df['Age']<60))
old = np.sum(df['Age']>=60)
print(young, adult, midage, old)

164+387+137+26

# If you want the minimum age of the passenger
np.min(df['Age'])

# if you want to know the max age of the passenger
np.max(df['Age'])

