# -*- coding: utf-8 -*-
"""Major Project 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fbFpVxMffHge6fz_KvqaO41xqcs9AZgA
"""

# Regressor
import pandas as pd
df = pd.read_csv('/content/Fish.csv')
df

x = df.loc[:,["Weight", "Length1", "Height"]].values
x

y = df.iloc[:,0].values

print(x)
print(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=0)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_pred

from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)*100

y_pred = model.predict([[242.    ,   30.    ,   11.52]])
y_pred

x_test

y_pred = model.predict([[19.9, 13.8, 2.9322]])
y_pred

y_pred = model.predict([[556.    ,   32.    ,   10.2565]])
y_pred

