# -*- coding: utf-8 -*-
"""Google.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kZ2Nq8sR-P8Jl6C5446VOSlHuyoqY8ez
"""

import pandas as pd
df = pd.read_csv('/content/Copy of sonar data.csv')
df

df.head()

df.describe()

x = df.iloc[:,1:60].values
y = df.iloc[:,-1].values
print(x)
print(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=0)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

model.score(x_test, y_test)

y_pred = model.predict(x_test)
y_pred

from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)*100