# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bh93iCJVwOeVYtYcC8cFC-iXPFey5tTz
"""

# Web scraping - Beautiful Soup
# Web scraping - Amazon customer review

import requests
from bs4 import BeautifulSoup as bs

url = 'https://www.amazon.in/product-reviews/B09G9GGCZ2/ref=cm_cr_othr_d_show_all_btm?ie=UTF8&reviewerType=all_reviews'
page = requests.get(url) # we are requesting the webpage of the url
page # <Response [200]> is correct <Response [503]> is error from the website
# If we dont get Response 200 rerun the cell again

page.content # here we have the source code of the customer review web page of amazon

# Let us get the source code in better readable format
soup = bs(page.content, 'html.parser')
soup

# Never ever consider Top +ve and Top critical reviews
names = soup.find_all('span', class_='a-profile-name')[2:]
names

len(names)

# now let us create a dataframe and put the names list in a new column in dataframe
import pandas as pd
df = pd.DataFrame(names, columns= {'Customer name'})

df

# next let us scrape the review title
r_title = soup.find_all('a', class_='review-title')
r_title

len(r_title)

# Data cleaning or data filtration
review_title = [] # empty list
for i in range(0,len(r_title)):
  review_title.append(r_title[i].get_text()[1:-1])
review_title

# Now slice the review dates
r_dates = soup.find_all('span', class_='review-date')[2:]
r_dates

len(r_dates)

review_date = []
for i in range(0, len(r_dates)):
  review_date.append(r_dates[i].get_text().replace('Reviewed in India 🇮🇳 on ', ''))
review_date

# Review rating in stars
rating = soup.find_all('i', class_='review-rating')[2:]
rating

len(rating)

review_rating = []
for i in range(0, len(rating)):
  review_rating.append(rating[i].get_text())
review_rating

# Review content
content = soup.find_all('span', class_='review-text')
content

len(content)

review_content = []
for i in range(0,len(content)):
  review_content.append(content[i].get_text()[1:-1])
review_content

df

df['Review Title'] = review_title
df

df['Review Date'] = review_date
df['Review Rating'] = review_rating
df['Review Content'] = review_content
df

df.to_csv('Amazon.csv')

